### ISSUE TITLE
Osmbonuspack 6.4 with Osmdroid 6.0

### ISSUE THREAD

**Issue by mlendl** [MKergall/osmbonuspack#320]
AFAIK Osmdroid 6.0 has huge rafactoring of Markers. One problem occurs with Osmbonuspack MarkerInfoWindow - the onOpen() is called many times. Please, please fix.

**Comment by MKergall** [comment]
Osmbonuspack 6.5 has just been released to upgrade to osmdroid 6.0.1. 
Can you try again with it?

**Comment by spyhunter99** [comment]
I'll have a look at it,  i think I know the cause

**Comment by mlendl** [comment]
Thank you. I see the ver 6.5 in the github, but Android Studio is not able to resolve it in build.gradle

**Comment by spyhunter99** [comment]
i think the issue is that we had to muck around with the mark info window rendering (when it's open). I think the current logic will trigger onOpen on every draw cycle if the window is open. I'll open an issue over there to track this

**Comment by spyhunter99** [comment]
@mlendl how is this triggering for you? Do you have a custom marker class or extended info window? i'm trying to get enough test classes together reproduce it

**Comment by mlendl** [comment]
Yes, I have extended MarkerInfoWindow class and onOpen() is called several
times when the window is being opened and also when map is moved. I added
one line check into my code, which ensures correct behaviour, so the issue
is not critical for me.

**Comment by MKergall** [comment]
Should be solved by commit #6dabd9c on osmdroid master.

**Comment by mlendl** [comment]
The problem with many times triggered onOpen() & onClose() still persists on 6.5.1. I have treated partly my code, but it is not perfect and there can be a performance issue.

**Comment by mlendl** [comment]
Thank you

**Comment by ostermannBernd** [comment]
MapQuestRoadManager of osmbonuspack 6.5.1 does not generate a correct BoundingBox.

public BoundingBox(final double north, final double east, final double south, final double west)

In MapQuestRoadManager the bounding box is created as:
 road.mBoundingBox = new BoundingBox(jBoundingBox.getDouble("maxLat"),
                    jBoundingBox.getDouble("minLng"), //East
                    jBoundingBox.getDouble("minLat"),
                    jBoundingBox.getDouble("maxLng")); //West

East should be: maxLng
West should be: minLng
